/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.13
 * Generated at: 2022-05-29 11:04:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Contact form</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\" integrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("      html, body {\r\n");
      out.write("      min-height: 100%;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: Roboto, Arial, sans-serif;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #666;\r\n");
      out.write("      }\r\n");
      out.write("      h1 {\r\n");
      out.write("      margin: 0 0 20px;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      color: #1c87c9;\r\n");
      out.write("      }\r\n");
      out.write("      p {\r\n");
      out.write("      margin: 0 0 5px;\r\n");
      out.write("      }\r\n");
      out.write("      .main-block {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      background: #1c87c9;\r\n");
      out.write("      }\r\n");
      out.write("      form {\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("      margin: 25px;\r\n");
      out.write("      box-shadow: 0 2px 5px #f5f5f5; \r\n");
      out.write("      background: #f5f5f5; \r\n");
      out.write("      }\r\n");
      out.write("      .fas {\r\n");
      out.write("      margin: 25px 10px 0;\r\n");
      out.write("      font-size: 72px;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      .fa-envelope {\r\n");
      out.write("      transform: rotate(-20deg);\r\n");
      out.write("      }\r\n");
      out.write("      .fa-at , .fa-mail-bulk{\r\n");
      out.write("      transform: rotate(10deg);\r\n");
      out.write("      }\r\n");
      out.write("      input, select {\r\n");
      out.write("      width: calc(100% - 18px);\r\n");
      out.write("      padding: 8px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      border: 1px solid #1c87c9;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      }\r\n");
      out.write("      input::placeholder {\r\n");
      out.write("      color: #666;\r\n");
      out.write("      }\r\n");
      out.write("      button {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      background: #1c87c9; \r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      button:hover {\r\n");
      out.write("      background: #2371a0;\r\n");
      out.write("      }    \r\n");
      out.write("      @media (min-width: 568px) {\r\n");
      out.write("      .main-block {\r\n");
      out.write("      flex-direction: row;\r\n");
      out.write("      }\r\n");
      out.write("      .left-part, form {\r\n");
      out.write("      width: 50%;\r\n");
      out.write("      }\r\n");
      out.write("      .fa-envelope {\r\n");
      out.write("      margin-top: 0;\r\n");
      out.write("      margin-left: 20%;\r\n");
      out.write("      }\r\n");
      out.write("      .fa-at {\r\n");
      out.write("      margin-top: -10%;\r\n");
      out.write("      margin-left: 65%;\r\n");
      out.write("      }\r\n");
      out.write("      .fa-mail-bulk {\r\n");
      out.write("      margin-top: 2%;\r\n");
      out.write("      margin-left: 28%;\r\n");
      out.write("      }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"main-block\">\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("      <form action=\"CreateEmployeeServlet\" method=\"post\">\r\n");
      out.write("        <h1>Create Employee</h1>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("          <input class=\"fname\" type=\"text\" name=\"empId\" placeholder=\"Employee ID\">\r\n");
      out.write("          <input type=\"text\" name=\"empName\" placeholder=\"Employee Name\">\r\n");
      out.write("          <input type=\"number\" name=\"empSal\" placeholder=\"Employee Salary\">\r\n");
      out.write("          <select name = \"empDept\">\r\n");
      out.write("          <Option>please select Department</Option>\r\n");
      out.write("          <Option>JAVA</Option>\r\n");
      out.write("          <Option>.NET</Option>\r\n");
      out.write("          <Option>PYTHON</Option>\r\n");
      out.write("          </select>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <button type=\"submit\" href=\"/\">Submit</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
